### ISSUE TITLE
有关C语言实现

### ISSUE THREAD

**Issue by qzwlecr** [FluorineDog/2016-uniquestudio-assignments2#1]
是否有必要加入init函数？
例如，array.h、vector.h中无法方便地初始化初始长度。

**Comment by klx3300** [comment]
今天写起来的时候我也发现了
没有构造函数好蛋疼

**Comment by FluorineDog** [comment]
同意，晚上加进去，你们先写其他的。

**Comment by klx3300** [comment]
然而我已经对头文件进行了魔改

2016年11月15日 上午11:50，"FluorineDog" notifications@github.com写道：

**Comment by FluorineDog** [comment]
已经merge
